version: '3.8'

services:
  mockit-routes:
    image: 'mockit-routes'
    build: 'mockit-routes'
    ports:
      - 3030:3030
    volumes:
      - ./configuration/routes.json:/usr/src/mockit-routes/configuration/routes.json
  mockit-server:
    image: 'mockit-server'
    build: 'server'
    ports:
      - 4040:4000
    volumes:
      - ./configuration/routes.json:/usr/src/mockit-server/configuration/routes.json
  mockit-client:
    image: 'mockit-client'
    build: 'client'
    ports:
      - 5050:3000
    environment:
      REACT_APP_MOCKIT_SERVER_URL : 'http://localhost:3030'
      REACT_APP_MOCKIT_API_URL : 'http://localhost:4040'
    volumes:
      - ./configuration/routes.json:/usr/src/mockit-client/src/config/routes.json
